# Creating a np array

In [1]:
import numpy as np

In [3]:
#Creating an array (Holds homogenous data)
arr = np.array([1,2,3]) 
arr

array([1, 2, 3])

In [7]:
#Creating a 2D array, auto structures it in an 2D format
matrix= [[1,2,3],[4,5,6],[7,8,9]]
npArray = np.array(matrix)
npArray


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Numpy methods

In [8]:
#NumPy funtions
#similar to the range()
np.arange(0,10,2) #(start, end, step). Start and End are inclusive & exclusive respectively

array([0, 2, 4, 6, 8])

In [10]:
#Creates Array of n zeros
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [11]:
#To create rows and columns of zeros, use inner parentheses
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#Similary, 
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
#start end inclusive and returns linearly/evenly spaced number n numbers (here 11)
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [43]:
#Returns identity matrix on NxN shape (one arg cuz Identity matrix is a square matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy Random library

In [18]:
#returns an uniform distribution(every number has same likelyhood of being chosen) of number from [1,0)
#returns NxN shape random nos., 5 rows 3 col here
#NO need of inner tuple for random lib
np.random.rand(5,3)

array([[0.63683943, 0.88017267, 0.95668819],
       [0.65837523, 0.12543889, 0.71436314],
       [0.9446657 , 0.55560204, 0.24990026],
       [0.61192643, 0.22074889, 0.86047889],
       [0.56833273, 0.6390065 , 0.61225334]])

In [20]:
#Returns a standard normal distribution whose mean is 0, thus is more likely to return nos. closer to 0
np.random.randn(3)

array([ 0.07093505, -0.30003674, -2.16439843])

In [22]:
np.random.randint(0,11,(5,3))#from (0 to 11], returns random integer of shape mxn array

array([[ 8,  1, 10],
       [ 9,  9,  1],
       [ 4,  2,  1],
       [ 2,  7,  5],
       [ 2,  6,  9]])

In [24]:
#Setting seed: Setting a seed number to a set of arbitary nos. This helps reproduce that random nos.
np.random.seed(42)#set a seed to the random distribution we get,so we can call that seed and itll reproduce same set of  nos.
np.random.randint(1,11,5)

array([7, 4, 8, 5, 7])

In [26]:
#Reproducing result by using same seed no. in the same block where we wanna reproduce the results
np.random.seed(42)#w/o this it'll not reproduce same results
np.random.randint(1,11,5)
#reproduces saem result as above block

array([7, 4, 8, 5, 7])

In [27]:
#NumPy attri & methods
arr = np.arange(0,25)
arr.reshape(5,5)#reshapes data into mxn structure if it fits into it, or else not

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Misc attr. and methods

In [29]:
# Prints max and min value on array
print(arr.min())
print(arr.max())

0
24


In [31]:
#prints index location of min and max element
arr.argmax()



24

In [32]:
arr.argmin()

0

In [33]:
#returning data type of array
arr.dtype

dtype('int64')

In [34]:

arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape# since reshaped, returns rows, col as shape

(5, 5)