# ZeroDivError

In [7]:
import numpy as np

In [8]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# We can perform arithmetic opertaion on arrays such as 
arr + 5 #Performs operation on each element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
arr * arr
#For this to work, the operands (arrays) need to have the same shape

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

* If numpy encounters a 0/0 or n/0, it'll throw a warning but still giving the output as nan(not a number) and inf(infinity) respectively

In [12]:
1/arr

/tmp/ipykernel_9118/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [14]:
arr/0

/tmp/ipykernel_9118/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
/tmp/ipykernel_9118/4291252909.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [17]:
# Universal funtions
np.sqrt(arr)
np.sin(arr)
np.log(arr)
np.var(arr)#variance
np.sum(arr)
np.std(arr)#std deviation and many more
# works on every single element

/tmp/ipykernel_9118/1421480172.py:4: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


3.1622776601683795

In [18]:
arr2d = np.arange(0,25).reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# to perform operation across an row or column
arr2d.sum(axis=0)#performs operation across rows i.e 0+5+10...

array([50, 55, 60, 65, 70])

In [20]:
arr2d.sum(axis=1)# performs across columns ie 0+1+2...

array([ 10,  35,  60,  85, 110])